language: android
jdk: oraclejdk8
android:
  components:
    # SDK Tools
    - platform-tools
    - tools

    # Build Tools
    - build-tools-24.0.0

    # SDK Version
    - android-24

    # Additional Components
    - extra-android-support
    - extra-android-m2repository

script: 
  - chmod +x gradlew
  - ./gradlew assembleDebug
