language: android
jdk: oraclejdk8
android:
  components:
    # SDK Tools
    - platform-tools
    - tools

    # Build Tools
    - build-tools-24.0.0

    # SDK Version
    - android-24

    # Additional Components
    - extra-android-support
    - extra-android-m2repository

before_script:
  - chmod +x gradlew
  - sed -i -e 's/Bot.USERNAME/"nope"/g' app/src/main/java/io/geeteshk/hyper/fragment/HelpFragment.java
  - sed -i -e 's/Bot.PASSWORD/"hahanochance"/g' app/src/main/java/io/geeteshk/hyper/fragment/HelpFragment.java

script: 
  - chmod +x gradlew
  - ./gradlew assembleDebug
